{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-proxyc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/proxyC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/proxyC/proxyC_{{ version }}.tar.gz
  sha256: ff5f11e8f5c896afead435573b75632e6102ea815861059d1b776c7f95be1f40

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - tbb-devel                    # [not win]
  host:
    - r-base
    - r-matrix >=1.2
    - r-rcpp >=0.12.12
    - r-rcpparmadillo >=0.7.600.1.0
    - libblas
    - liblapack
    - tbb-devel                    # [not win]
  run:
    - r-base
    - r-matrix >=1.2
    - r-rcpp >=0.12.12
    - r-rcpparmadillo >=0.7.600.1.0

test:
  commands:
    - $R -e "library('proxyC')"           # [not win]
    - "\"%R%\" -e \"library('proxyC')\""  # [win]

about:
  home: https://github.com/koheiw/proxyC
  license: GPL-3.0-only
  summary: ' Computes proximity between rows or columns of large matrices efficiently in C++. Functions are optimised for large sparse matrices using the Armadillo and Intel TBB libraries. Among several built-in similarity/distance measures, computation of correlation, cosine similarity and Euclidean distance is particularly
    fast. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
