appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: CSciiTcDGH+c8MaNfeRdYm4SkZcm4Lhx4zvjxfF/Rmr8BJIMgvESRfoZEjM0pu4xiDnSiQ6qAzHyU28bhRaCevCO5BfWimPin58tZjgUpV5kKeFvCPCDfcVff5Idm/8/OtXs45y6dXnagG7fSa6C9atiG1xPYGWcvXwpeJuTKvead3wFAzT5m6B4n2TBaCg2HrztUWph6cnJbIKQ1jmYu4CST5VSjO8nmaWNU0Wn/7z1dpEGAUoIvuM+NAFWGpzoQQPQxMBevG2pNiJIf4faahxf0efygbLiXANdnYa56WE9CM+Q6flXOMRjCaxIdV03Zjt5iKA4tY6x4bTF8gUz3o8sS4kSYE0KFhh6yXHsiAX98K0ddYO7qgc3YfZdojBaExN/uhKm7jhO20iSbVfKgcl60SzfaYq5i3MvLnRFM6Ab93vsDaDEewiNvR8sFUCMnGochEQoKtIxyDwTTNh+GNGmc2WvIZzskmNCaSqakwjP6b2R+MlXvp4HR/MNbB2IFxiBfWRLIIH4/WgL+jtvwYsDu9HJOm7dM1nWKT2X2Y0IyUtFciQawTcgULLVV0/F1SEpTk/vsBQsomdjYV3mvRpV1CEZP+zs63iCGyemsLtBTO2FKfNo9VC6dGaNZn1qiR4PACvYYyMOCAKk8dxcpFNMiK+yvLJ++QB41eXLHxg=}
bot:
  automerge: true
